Using base prefix '/usr'
New python executable in /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3
Not overwriting existing python script /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python (you must use /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3)
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.0.0)
----------------------------------------------------
Checking source files for common errors in following
directories:
fabric8a_auth tests
----------------------------------------------------

fabric8a_auth/fabric8a_auth.py
fabric8a_auth/fabric8a_auth.py:8: 'jwt.contrib.algorithms.pycrypto.RSAAlgorithm' imported but unused
fabric8a_auth/fabric8a_auth.py:77: redefinition of unused 'get_audiences' from line 15
    Fail
fabric8a_auth/__init__.py
    Pass
fabric8a_auth/errors.py
    Pass
tests/test_errors_class.py
tests/test_errors_class.py:3: 'unittest' imported but unused
tests/test_errors_class.py:17: local variable 'e' is assigned to but never used
    Fail
tests/__init__.py
    Pass
tests/test_user_class.py
tests/test_user_class.py:3: 'unittest' imported but unused
    Fail
tests/test_token_handling.py
tests/test_token_handling.py:3: 'from unittest.mock import *' used; unable to detect undefined names
tests/test_token_handling.py:71: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:73: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:80: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:82: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:90: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:92: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:100: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:102: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:110: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:112: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:120: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:122: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:134: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:136: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:149: 'patch' may be undefined, or defined from star imports: unittest.mock
tests/test_token_handling.py:151: 'patch' may be undefined, or defined from star imports: unittest.mock
    Fail
----------------------------------------------------
Checking following source files for common errors:
setup.py
----------------------------------------------------

setup.py
    Pass
4 source files out of 8 files needs to be checked and fixed
